version: '3'

services:
###> doctrine/doctrine-bundle ###
    database:
        image: mysql:${MYSQL_VERSION:-8}
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-su_myapp}
            # You should definitely change the password in production
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMe}
        volumes:
            - db-data:/var/lib/mysql
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
    db-data:
###< doctrine/doctrine-bundle ###
