sulu_document_manager:
    sessions:
        default:
            backend:
                caches:
                    meta: doctrine_phpcr.meta_cache_provider
                    nodes: doctrine_phpcr.nodes_cache_provider
        live:
            backend:
                caches:
                    meta: doctrine_phpcr.meta_cache_provider
                    nodes: doctrine_phpcr.nodes_cache_provider

services:
    doctrine_phpcr.meta_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine_phpcr.meta_cache_pool'
        tags:
            - { name: 'kernel.reset', method: 'reset' }

    doctrine_phpcr.nodes_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine_phpcr.nodes_cache_pool'
        tags:
            - { name: 'kernel.reset', method: 'reset' }

framework:
    cache:
        pools:
            doctrine_phpcr.meta_cache_pool:
                adapter: cache.app

            doctrine_phpcr.nodes_cache_pool:
                adapter: cache.app
